### ISSUE TITLE
Some programs wouldn't display images correctly

### ISSUE THREAD

**Issue by ersmiller** [mansuf/mangadex-downloader#10]
As a way to help organize files for some programs, and have a cleaner look, it would be nice to add one or more leading zeroes for files and folders.

For example, instead of:
page 8.jpg
page 9.jpg
page 10.jpg
...
page 105.jpg

Have the files titled:
page 008.jpg
page 009.jpg
page 010.jpg
page 105.jpg

Some programs display the pages out of order without this.

**Comment by mansuf** [comment]
> Some programs display the pages out of order without this.

I'm curious, which `--save-as` format have caused this problem ?

And, what program did you use ?

**Comment by ersmiller** [comment]
The save as format doesn't matter (I tried both individual jpg files and cbz), it's just that some programs don't sort correctly when there's no leading zeroes in the file names.

  For instance, one file that got saved had the filename of:
x9-c480c1b10368c98875e3ad90eb65d4f3c538010b63488e35b3d64eb08fda8d5a
  The next one was:
x10-19fe790e2c32d26a846965f8364520bccdf61667dbc157d94c493d0e4986c6fc

  No leading zero for files before the 10th caused PicWalk to display the pages in the following order:

1
10
11
12
...etc.
19
2
20
21
...etc.
29
3
31
32
...etc.

  Some programs sort based on the first digit or letter it finds without looking further to see if there's more to the number.  This means that 10 comes in between 1 and 2 while 20 comes in between 2 and 3.
  If every number had the same amount of digits (001, 002, 010, 011, 020, 021, 100, etc.), this would not be a problem.

  If I remember correctly, older versions of Windows sorted the same way.

**Comment by mansuf** [comment]
This feature has been added as `--enable-legacy-sorting` option. But, i'm unable to test it in live application that have sorting like that. I have created separate repository ([feature/legacy-sorting](https://github.com/mansuf/mangadex-downloader/tree/feature/legacy-sorting)) in case you wanna do some testing.

You can re-open this issue or open a new one if you found the problem related to legacy sorting

**Comment by ersmiller** [comment]
Sorry, I'm not exactly sure what to do.  I'm not really familiar with github.  Do I download a new version or compile compile something?  If the latter ... how?

**Comment by mansuf** [comment]
Unfortunately, if you unfamiliar with git, python, and terminal stuffs. The only solution is wait until v1.0.0 is released.

However, if you really want to try it out:
- You must have python installed with minimum version 3.8+
- Download whole repository in a zip file here -> https://github.com/mansuf/mangadex-downloader/archive/refs/heads/feature/legacy-sorting.zip
- Extract the zip file, open a terminal, and then run `python3 setup.py install` and you're finished.

I'm sorry cannot help you further. This is the best i can do.

**Comment by ersmiller** [comment]
Well, step 1 and 2 I had already managed.  It's step 3 that I can't get through.

  Putting in the python3 setup.py install command appears to silently fail in a CMD or PowerShell window.  I've done programming before in school (BASIC, C++, C#, JAVA), but all the editors I've used have an actual compile command.  I'm at a loss with Python.

  And now I feel old.
________________________________
