### ISSUE TITLE
Downloading from private MDList with use_volume_cover set as true causes it to crash when using cbz-volume mode

### ISSUE THREAD

**Issue by Razzeli** [mansuf/mangadex-downloader#100]
### What happened ?

Sorry to bother you again. The problem I am having now is with both v2.10.3 and v3.0.0 latest test version. When I try to download from my private MDList, when using cbz-volume and volume cover set as true, it crashes in the beginning. I tried with multiple different mangas, with same result.

My config is as follows on v3.0.0:

mangadex-dl "conf"

Config 'login_cache' is set to False
Config 'language' is set to 'en'
Config 'cover' is set to 'none'
Config 'save_as' is set to 'cbz-volume'
Config 'use_chapter_title' is set to False
Config 'use_compressed_image' is set to False
Config 'force_https' is set to False
Config 'path' is set to 'Y:/Test_Mangadex/{manga.title}'
Config 'filename_chapter' is set to '{manga.title} {chapter.simple_name}{file_ext}'
Config 'filename_volume' is set to '{manga.title} Vol. {volume}{file_ext}'
Config 'filename_single' is set to 'All chapters{file_ext}'
Config 'dns_over_https' is set to None
Config 'no_group_name' is set to True
Config 'sort_by' is set to 'volume'
Config 'no_progress_bar' is set to False
Config 'http_retries' is set to 5
Config 'write_tachiyomi_info' is set to False
Config 'download_mode' is set to 'default'
Config 'use_chapter_cover' is set to False
Config 'use_volume_cover' is set to True
Config 'no_track' is set to False
Config 'volume_cover_language' is set to 'ja'
Config 'stacked_progress_bar_order' is set to 'volumes, chapters, pages, file sizes, convert'
Config 'log_level' is set to 'INFO'
Config 'progress_bar_layout' is set to 'default'
Config 'ignore_missing_chapters' is set to False
Config 'create_no_volume' is set to False

I used the command:

mangadex-dl "list" --login --delay-requests 0.5

and the error I am getting is when I have logged in and selected the MDList I wanted:

[INFO] Checking url = 93e8bbad-31d4-43fa-8324-fdeae9e42c6e
[INFO] Using English language
[INFO] Fetching all chapters...
[INFO] Download directory is set to "\\w0-NAS\Media2\Test_Mangadex\Asahina-san no Bentou Tabetai"
[INFO] Using cbz-volume format
[INFO] Downloading cover manga Asahina-san no Bentou Tabetai
[INFO] Not downloading cover manga, since "cover" is none
[INFO] Preparing to download
[INFO] Getting volume cover for "Volume 1"
[ERROR] We have problem in queue worker
Traceback (most recent call last):
  File "mangadex_downloader\utils.py", line 238, in run
  File "mangadex_downloader\format\comic_book.py", line 159, in <lambda>
  File "zipfile.py", line 1741, in write
  File "zipfile.py", line 504, in from_file
FileNotFoundError: [WinError 2] Määritettyä tiedostoa ei löydy: 'Y:\\Test_Mangadex\\Asahina-san no Bentou Tabetai\\Vol. 1\\000.png'
[ERROR] Unhandled exception, FileNotFoundError: [WinError 2] Määritettyä tiedostoa ei löydy: 'Y:\\Test_Mangadex\\Asahina-san no Bentou Tabetai\\Vol. 1\\000.png'
Traceback (most recent call last):
  File "mangadex_downloader\cli\__init__.py", line 87, in _main
  File "mangadex_downloader\cli\download.py", line 34, in download
  File "mangadex_downloader\cli\url.py", line 187, in __call__
  File "mangadex_downloader\cli\url.py", line 156, in download_list
  File "mangadex_downloader\main.py", line 253, in download_list
  File "mangadex_downloader\main.py", line 195, in download
  File "mangadex_downloader\main.py", line 145, in download_manga
  File "mangadex_downloader\format\base.py", line 728, in main
  File "mangadex_downloader\format\base.py", line 677, in download_volumes
  File "mangadex_downloader\format\comic_book.py", line 193, in on_prepare
  File "mangadex_downloader\format\comic_book.py", line 159, in insert_vol_cover_img
  File "mangadex_downloader\utils.py", line 217, in submit
  File "mangadex_downloader\utils.py", line 238, in run
  File "mangadex_downloader\format\comic_book.py", line 159, in <lambda>
  File "zipfile.py", line 1741, in write
  File "zipfile.py", line 504, in from_file
FileNotFoundError: [WinError 2] Määritettyä tiedostoa ei löydy: 'Y:\\Test_Mangadex\\Asahina-san no Bentou Tabetai\\Vol. 1\\000.png'

I noticed that it gets the error when it tries to download the volume cover, so when I tried it without volume cover, it kinda worked, but still with some network errors from the beginning of each chapter. Might be on my end, so I tried also with VPN plus force-https and dns-over-https options at different times, but no difference. Not sure if it could also be an issue on MangaDex's end.

This is when I tried again without volume cover, when it sorta works:

[INFO] Checking url = 93e8bbad-31d4-43fa-8324-fdeae9e42c6e
[INFO] Using English language
[INFO] Fetching all chapters...
[INFO] Download directory is set to "\\w0-NAS\Media2\Test_Mangadex\Asahina-san no Bentou Tabetai"
[INFO] Using cbz-volume format
[INFO] Downloading cover manga Asahina-san no Bentou Tabetai
[INFO] Not downloading cover manga, since "cover" is none
[INFO] Preparing to download
[INFO] Getting images from chapter 1
[INFO] Downloading Volume. 1 Chapter. 1 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 1
[INFO] Downloading Volume. 1 Chapter. 1 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 1
[INFO] Downloading Volume. 1 Chapter. 1 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 1
[INFO] Downloading Volume. 1 Chapter. 1 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 1
[INFO] Downloading Volume. 1 Chapter. 1 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 1
[INFO] Downloading Volume. 1 Chapter. 1 page 1
File sizes: 100%|████████████████████████████| 696k/696k [00:00<00:00, 7.04MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 2
File sizes: 100%|██████████████████████████| 1.63M/1.63M [00:00<00:00, 11.3MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 3
File sizes: 100%|████████████████████████████| 349k/349k [00:00<00:00, 19.5MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 4
File sizes: 100%|████████████████████████████| 389k/389k [00:00<00:00, 19.3MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 5
File sizes: 100%|████████████████████████████| 329k/329k [00:00<00:00, 20.5MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 6
File sizes: 100%|████████████████████████████| 263k/263k [00:00<00:00, 17.4MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 7
File sizes: 100%|████████████████████████████| 468k/468k [00:00<00:00, 19.5MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 8
File sizes: 100%|████████████████████████████| 279k/279k [00:00<00:00, 18.2MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 9
File sizes: 100%|████████████████████████████| 455k/455k [00:00<00:00, 20.7MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 10
File sizes: 100%|████████████████████████████| 354k/354k [00:00<00:00, 20.2MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 11
File sizes: 100%|████████████████████████████| 389k/389k [00:00<00:00, 20.5MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 12
File sizes: 100%|████████████████████████████| 533k/533k [00:00<00:00, 21.9MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 13
File sizes: 100%|████████████████████████████| 586k/586k [00:00<00:00, 22.5MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 14
File sizes: 100%|████████████████████████████| 466k/466k [00:00<00:00, 21.2MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 15
File sizes: 100%|████████████████████████████| 456k/456k [00:00<00:00, 21.7MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 16
File sizes: 100%|████████████████████████████| 531k/531k [00:00<00:00, 21.2MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 17
File sizes: 100%|████████████████████████████| 510k/510k [00:00<00:00, 21.1MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 18
File sizes: 100%|████████████████████████████| 509k/509k [00:00<00:00, 21.2MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 19
File sizes: 100%|████████████████████████████| 660k/660k [00:00<00:00, 21.9MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 20
File sizes: 100%|████████████████████████████| 620k/620k [00:00<00:00, 22.2MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 21
File sizes: 100%|████████████████████████████| 407k/407k [00:00<00:00, 19.9MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 22
File sizes: 100%|████████████████████████████| 390k/390k [00:00<00:00, 20.4MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 23
File sizes: 100%|████████████████████████████| 375k/375k [00:00<00:00, 20.0MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 24
File sizes: 100%|████████████████████████████| 389k/389k [00:00<00:00, 20.3MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 25
File sizes: 100%|████████████████████████████| 398k/398k [00:00<00:00, 20.8MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 26
File sizes: 100%|████████████████████████████| 371k/371k [00:00<00:00, 19.9MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 27
File sizes: 100%|████████████████████████████| 393k/393k [00:00<00:00, 20.4MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 28
File sizes: 100%|████████████████████████████| 408k/408k [00:00<00:00, 21.5MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 29
File sizes: 100%|████████████████████████████| 474k/474k [00:00<00:00, 21.3MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 30
File sizes: 100%|████████████████████████████| 629k/629k [00:00<00:00, 22.3MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 31
File sizes: 100%|████████████████████████████| 641k/641k [00:00<00:00, 22.5MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 32
File sizes: 100%|████████████████████████████| 543k/543k [00:00<00:00, 21.7MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 33
File sizes: 100%|████████████████████████████| 628k/628k [00:00<00:00, 21.9MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 34
File sizes: 100%|████████████████████████████| 889k/889k [00:00<00:00, 18.7MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 35
File sizes: 100%|████████████████████████████| 571k/571k [00:00<00:00, 22.9MB/s]
[INFO] Downloading Volume. 1 Chapter. 1 page 36
File sizes: 100%|████████████████████████████| 117k/117k [00:00<00:00, 13.7MB/s]
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
[ERROR] One of MangaDex network is failing, re-fetching the images...
[INFO] Getting images from chapter 2
[INFO] Downloading Volume. 1 Chapter. 2 page 1
File sizes: 100%|████████████████████████████| 684k/684k [00:00<00:00, 20.5MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 2
File sizes: 100%|████████████████████████████| 521k/521k [00:00<00:00, 17.3MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 3
File sizes: 100%|████████████████████████████| 608k/608k [00:00<00:00, 21.4MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 4
File sizes: 100%|████████████████████████████| 548k/548k [00:00<00:00, 22.8MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 5
File sizes: 100%|████████████████████████████| 598k/598k [00:00<00:00, 21.8MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 6
File sizes: 100%|████████████████████████████| 498k/498k [00:00<00:00, 21.7MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 7
File sizes: 100%|████████████████████████████| 418k/418k [00:00<00:00, 20.0MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 8
File sizes: 100%|████████████████████████████| 426k/426k [00:00<00:00, 21.2MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 9
File sizes: 100%|████████████████████████████| 401k/401k [00:00<00:00, 21.3MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 10
File sizes: 100%|████████████████████████████| 697k/697k [00:00<00:00, 22.6MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 11
File sizes: 100%|████████████████████████████| 476k/476k [00:00<00:00, 21.4MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 12
File sizes: 100%|████████████████████████████| 384k/384k [00:00<00:00, 21.0MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 13
File sizes: 100%|████████████████████████████| 462k/462k [00:00<00:00, 18.1MB/s]
[INFO] Downloading Volume. 1 Chapter. 2 page 14
File sizes: 100%|████████████████████████████| 515k/515k [00:00<00:00, 22.1MB/s]

an so on.

However if I made the test MDList public and downloaded it without logging in, it worked fine, however unfortunately my "main" MDLists are too big, that they apparently cannot be changed to public at the moment.

### What did you expect to happen ?

Downloads similarly like text files including mangadex urls.

### OS version

Windows 11

### App version

v2.10.3 and v3.0.0 latest test version

### Installation origin

Github releases

### Reproducible command

mangadex-dl "list" --login --delay-requests 0.5

**Comment by mansuf** [comment]
Hello, this bug has been fixed in commit https://github.com/mansuf/mangadex-downloader/commit/2c9f62dadcf2d555b674a0fb41d15651cfdfad9f. You can try it by installing development version.

Installation method with pip & git:

```
pip uninstall mangadex-downloader
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@0d0e724975f8ec963f46d9a9dea2e58d6f6adf19
```

Installation from Github Release:

You can download it from here (in "artifacts" section) -> https://github.com/mansuf/mangadex-downloader/actions/runs/8518332683

If you have an problem, please let me know 👍
