### ISSUE TITLE
Add a option to automatic download new ongoing chapter

### ISSUE THREAD

**Issue by GeekLuffy** [mansuf/mangadex-downloader#101]
### The idea

Add a option to automatic download new ongoing chapter

### Why this feature should be added to the app ?

It could be a great thing

**Comment by Treast** [comment]
That would be great, with a way to notify when a new chapter is downloaded (Discord webhook, Telegram...)

**Comment by mansuf** [comment]
Can i ask what type of automatic did you mean ?

Like for example in Linux you can create cron job (On windows is called Task Scheduler) for mangadex-downloader and it will automatically run the application based on specific configurations.

Or did you mean you wanna suggest an option that can run indefinitely ?

**Comment by GeekLuffy** [comment]
i mean like rss feeds like we subscribe a manga then it will automatically download new chapter of it as soon as it release
i will be a great help

**Comment by mansuf** [comment]
Unfortunately, MangaDex doesn't provide RSS feeds anymore, so the only option is run indefinitely or create job schedule in cron (Linux) or Task Scheduler (Windows), i have no idea what's job scheduler app in Mac OS.

Run indefinitely is basically give multiple urls or single url to mangadex-downloader and the application will periodically check if there is new chapters and if there is new chapters it will try to download it. The application will run forever and stays in loop untill you shut it down manually (or the app is crashing).

**Comment by GeekLuffy** [comment]
i have a site which can generate mangadex rss i used it before it works well

**Comment by GeekLuffy** [comment]
So can you make something so it will be able to download mangaplus chapters also

**Comment by mansuf** [comment]
> So can you make something so it will be able to download mangaplus chapters also

I have talked about it, you can see it here https://github.com/mansuf/mangadex-downloader/issues/90#issuecomment-1740221701

<details>
  <summary>Spoiler alert</summary>
  
  The answer is no
    
</details>

**Comment by mansuf** [comment]
Hello, This feature has been added in commit https://github.com/mansuf/mangadex-downloader/commit/725dd7fffa11103b2680b6adb9921c1878cdd300. You can test it by installing development version.

Installation with Git & Pip:

```sh
pip uninstall mangadex-downloader
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@725dd7fffa11103b2680b6adb9921c1878cdd300
```

Installation from Github Artifact CI (bundled executable):

You can download it from [here](https://github.com/mansuf/mangadex-downloader/actions/runs/10536827748) in "artifacts" section

-----------

Usage

```
mangadex-dl "insert mangadex url here" --run-forever
```

The application will run forever and have 5 seconds delay before starting download again.

If you have problem or bugs, let me know 👍.

**Comment by GeekLuffy** [comment]
Thanks Buddy
