### ISSUE TITLE
Add an option to not embed ComicInfo.xml file in cbz format

### ISSUE THREAD

**Issue by qx6ghqkz** [mansuf/mangadex-downloader#104]
### The idea

Add an option such as `--no-comicinfo` to disable embedding a `ComicInfo.xml` file into the `cbz` format and any other supported formats, or disable this functionality by default and make it optional with an option such as `--write-comicinfo`.

### Why this feature should be added to the app ?

A `ComicInfo.xml` file is not always wanted as it may contain metadata that causes manga to be displayed differently than a user wants in supported comic readers (e.g. Komga). It would be nice to have an option to disable the generation of this file instead of having to manually delete or modify the file for each download.

**Comment by mansuf** [comment]
Thanks for the idea 👍, i will add this feature as `--no-metadata` option.

**Comment by mansuf** [comment]
Hello, this feature has been added in commit https://github.com/mansuf/mangadex-downloader/commit/b369f226050ef5cd4a026b9fcb15762c4b604d5f. You can test it by installing development version.

Installation with Git & Pip:

```sh
pip uninstall mangadex-downloader
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@b369f226050ef5cd4a026b9fcb15762c4b604d5f
```

Installation from Github Artifact CI:

You can download it from [here](https://github.com/mansuf/mangadex-downloader/actions/runs/9509899620) in "artifacts" section

-----------

Usage

```
mangadex-dl "URL" -f "cbz" --no-metadata
```

If you have problem or bugs, let me know 👍
