### ISSUE TITLE
Add url to ComicInfo.xml

### ISSUE THREAD

**Issue by vonProteus** [mansuf/mangadex-downloader#108]
### The idea

can you add url of chapter to ComicInfo.xml in cbz

### Why this feature should be added to the app ?

when looking at chapter (cbz) it would be nice to have url of orginal location

**Comment by vonProteus** [comment]
i think it is `web` tag 
https://anansi-project.github.io/docs/comicinfo/documentation#web

**Comment by mansuf** [comment]
`web` tag has been added in https://github.com/mansuf/mangadex-downloader/commit/a76e05d674e24ac75cc4838f71e33b9f56e3ff77. You can try installing development version if you want to test it.

Installtion with Git & pip

```sh
pip uninstall mangadex-downloader
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@40041783ec97ec92ad8ec08f4888f280beb8cede
```

**Comment by mansuf** [comment]
`web` tag has been added in https://github.com/mansuf/mangadex-downloader/commit/a76e05d674e24ac75cc4838f71e33b9f56e3ff77. You can try installing development version if you want to test it.

Installtion with Git & pip

```sh
pip uninstall mangadex-downloader
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@a76e05d674e24ac75cc4838f71e33b9f56e3ff77
```

**Comment by vonProteus** [comment]
i think it should be url to chapter not title ^_^
or maybe `title_URL chapter_URl`
> [Web](https://anansi-project.github.io/docs/comicinfo/documentation#web)
>
> A URL pointing to a reference website for the book.
>
> It is accepted that multiple values are space separated. If a space is a part of the url it must be [percent encoded](https://datatracker.ietf.org/doc/html/rfc2396#section-2.4.1).

**Comment by mansuf** [comment]
Oh right, i was messed up, sorry. I will repair it soon.

**Comment by mansuf** [comment]
Done, it was fixed https://github.com/mansuf/mangadex-downloader/commit/2f72a08867db0064647ad1add9b5213b91e1c30c. Originally i was added for cbz-volume and cbz-single. Now when `cbz` format is used it gets to chapter URL, but if `cbz-volume` or `cbz-single` is used it gets to manga URL

**Comment by mansuf** [comment]
Hold up, i messed up again, i'm really sorry for this, it's 2 am right now i'm really sleepy.

**Comment by mansuf** [comment]
Alright, it should REALLY FIXED in https://github.com/mansuf/mangadex-downloader/commit/ae3ab36cd2cc4b8ac2cfd241fae5ac604af4093e.

If you found any bugs with this patch, let me know
