### ISSUE TITLE
Option to download chapters by all groups: -a/--all

### ISSUE THREAD

**Issue by AncientMicrowave** [mansuf/mangadex-downloader#111]
### The idea

Add a -a or --all option to download chapters by all groups that have released them

### Why this feature should be added to the app ?

This will make it unnecessary to explicitly specify certain groups in a series of commands, allowing the user to sort through them himself later

**Comment by mansuf** [comment]
I think that option is already exists, but i forgot to write documentation about it. You can use `--group` option with value `all`

```sh
# This will download all groups each chapter 
mangadex-dl "insert MangaDex URL" --group all 
```

Sorry about that, i will add this into documentation in next version release
