### ISSUE TITLE
add end/start volume option

### ISSUE THREAD

**Issue by rodrigo-sys** [mansuf/mangadex-downloader#112]
### The idea
An option analogous to  `--start-chapter` and `--end-chapter`, but for volumes.

### Why this feature should be added to the app ?

it would be nice to have the option to choose the range of  downloads in volumes.

**Comment by mansuf** [comment]
I will working on it soon, right now i wanna re-work the `--range` option it has been a year that option is staying there and has been disabled.

Thanks for the idea !
