### ISSUE TITLE
Feature to Download all the cover of a manga

### ISSUE THREAD

**Issue by sambt22022517** [mansuf/mangadex-downloader#115]
### The idea

Why don't you add a feature for automatically download all of the available covers ? Like `mangadex-dl "all-cover:manga_url"`. The part which is in front of `cover` is for `all` (mean: download all of covers) or `one` (mean: select one of available covers to download) and default is `one`. And the `new-cover:manga_url` command is to download all the cover which is not in my folder.

### Why this feature should be added to the app ?

Everytime I want to download the cover of a manga, I must run the command `mangadex-dl "cover:manga_url"` many times if the manga has many volumns because each time i can only choose 1 cover for downloading. It's so tired.

**Comment by mansuf** [comment]
There is option called `--input-pos` with value `*` that you can use to automatically download all the covers. And this option can be used for basically any commands.

For example:

```sh
# Download all covers from a manga
mangadex-dl "cover:manga_url" --input-pos "*"

# Download all manga from library
mangadex-dl "library" --login --input-pos "*"

# Download all list from logged in user
mangadex-dl "list" --login --input-pos "*"
```

I forgot to add this option in the documentation (both in the app and website). I apologies 🙏, i will add this in my to-do list
