### ISSUE TITLE
failed to connect mangadex API

### ISSUE THREAD

**Issue by zandrake417** [mansuf/mangadex-downloader#123]
### What happened ?

i cannot download the manga, then show this error:
 Failed connect to "https://api.mangadex.org/manga/c1e284bc-0436-42fe-b571-fa35a94279ce", reason: HTTPSConnectionPool(host='api.mangadex.org', port=443): Max retries exceeded with url:

### What did you expect to happen ?

the download success

### OS version

Windows 10

### App version

mangadex-downloader v2.10.3 (https://github.com/mansuf/mangadex-downloader)
Python: 3.12.7
arch: x64
bundled executable: no

### Installation origin

PyPI (Python Package Index)

### Reproducible command

mangadex-dl "link"

**Comment by B17C0D3** [comment]
this is not a but
mangadex is blocking you for too fast loading
tomorrow you can try to add this parameter to slow down
--delay-requests 0.3

**Comment by zandrake417** [comment]
turn out, look like my ISP blocking mangadex, an then when i use cloudflare. It's solve the issue
