### ISSUE TITLE
[Feature Request] Group chapters into volumes

### ISSUE THREAD

**Issue by lofilobzik** [mansuf/mangadex-downloader#13]
...for easier navigation. I feel there should be an optional flag to put chapters into "Volume n" folders if "pdf" or "cbz" flags are present. Or if, for example, "pdf-chapters" or "cbz-chapters" flags are there, group them into "Volume n.pdf" files. Sort of like middle ground between downloading all the chapters into the same folder and making a large pdf file with all the chapters.

Like so:

![Screenshot from 2022-04-02 21-34-51](https://user-images.githubusercontent.com/75563134/161396763-cd63ae2b-ce70-49fb-8e7b-4fa4fdc52c2f.png)

and

![Screenshot from 2022-04-02 21-05-11](https://user-images.githubusercontent.com/75563134/161396766-2ecce510-eb80-450e-8f6f-ee41c8b54039.png)

_I have discovered your project this evening and was astounded by how flawlessly it works (except for missing arial fonts, which is fixable on my part). Thank you for your work!_

**Comment by mansuf** [comment]
> I feel there should be an optional flag to put chapters into "Volume n" folders if "pdf" or "cbz" flags are present

But, in the picture 1 it shows chapters stored in each volume folder which means lead to `raw` format.

**Comment by lofilobzik** [comment]
> But, in the picture 1 it shows chapters stored in each volume folder which means lead to `raw` format.

Oh, I just meant that translated chapter pdf-s are sorted into folders.

**Comment by mansuf** [comment]
I prefer picture 2 tbh than picture 1, because it wrap "all chapters from volume n" to one single file.

**Comment by mansuf** [comment]
Added in https://github.com/mansuf/mangadex-downloader/commit/60494bc45ed3633a5abfc1d71171a04aa4c08534, https://github.com/mansuf/mangadex-downloader/commit/dd76e184ec7395408c898a2b52abcdb98865e38d, https://github.com/mansuf/mangadex-downloader/commit/47d738e9b3da35794945ef228b92229ac02b3b06

**Comment by Arnfild** [comment]
> Added in [60494bc](https://github.com/mansuf/mangadex-downloader/commit/60494bc45ed3633a5abfc1d71171a04aa4c08534), [dd76e18](https://github.com/mansuf/mangadex-downloader/commit/dd76e184ec7395408c898a2b52abcdb98865e38d), [47d738e](https://github.com/mansuf/mangadex-downloader/commit/47d738e9b3da35794945ef228b92229ac02b3b06)
cbz-volume format would also be handy
