### ISSUE TITLE
[Feature Request] cbz-volume format

### ISSUE THREAD

**Issue by Arnfild** [mansuf/mangadex-downloader#15]
Greetings. Appreciate your work on mangadex-downloader, that's a handy tool!

Earlier there was a request for grouping volume chapters files into standalone volume files: 
https://github.com/mansuf/mangadex-downloader/issues/13#issue-1190710891
For some reason only **pdf-volume** format was added, while there are people who prefer cbz.

**Comment by mansuf** [comment]
I did add `cbz-volume` format, you can take look at commit history [here](https://github.com/mansuf/mangadex-downloader/commit/dd76e184ec7395408c898a2b52abcdb98865e38d)

**Comment by Arnfild** [comment]
> I did add `cbz-volume` format, you can take look at commit history [here](https://github.com/mansuf/mangadex-downloader/commit/dd76e184ec7395408c898a2b52abcdb98865e38d)

I see. Apparently it's the standalone version that is outdated

**Comment by mansuf** [comment]
The stable version (v0.6.1) doesn't have this features yet. Currently working on v1.0.0, take a look at the progress [here](https://github.com/mansuf/mangadex-downloader/projects/1). You can install dev version (from branch `main`) if you want to try this features early.
