### ISSUE TITLE
[Bug] cbz-volume 'ImageFont' is not defined

### ISSUE THREAD

**Issue by Arnfild** [mansuf/mangadex-downloader#16]
Hey. I've installed the latest version and tried to download manga in **cbz-volume** format. 
Here is the log: https://pastebin.com/p0wDSLYN
The problem occurs not with that particular manga, but with any when saving in **cbz-volume** format. Saving in other formats works properly.

**Comment by mansuf** [comment]
Seems like you don't have [Pillow](https://pypi.org/project/Pillow/) installed, any `volume` format require that.

My bad, i didn't provide detailed error for `cbz-volume`. It should be throwing error `Pillow is not installed`

**Comment by Arnfild** [comment]
> Seems like you don't have [Pillow](https://pypi.org/project/Pillow/) installed, any `volume` format require that.
> 
> My bad, i didn't provide detailed error for `cbz-volume`. It should be throwing error `Pillow is not installed`

Yep, that was the issue. Now it seems to be working flawlessly. Thank you!
