### ISSUE TITLE
[Feature Request] cb7 format support

### ISSUE THREAD

**Issue by rokibhasansagar** [mansuf/mangadex-downloader#17]
I like the features of your work 😍 

If it's not too hard, I'd like to ask if you could implement 7-zip compression support for tachiyomi such that we can download as `tachiyomi-7zip` format with `*.7z` files.

7-zip can compress files better than Zip, and it can save some storage data (about 3-10% for image files) as-well-as reduce downloadable size for individual chapters/volumes when hosted on certain website/server.

**Comment by mansuf** [comment]
I'm not sure if tachiyomi support `.7z` files, the [documentation](https://tachiyomi.org/help/guides/local-manga) says

> Supported chapter formats are folder with pictures inside (such as .jpg, .png, etc), ZIP/CBZ, RAR/CBR and EPUB

**Comment by rokibhasansagar** [comment]
Maybe I didn't express myself clearly.

By "tachiyomi", I didn't mean the "Tachiyomi.org Manga Format", rather just the naming option as per mangadex-dl CLI.

With "tachiyomi-zip" format option in CLI, I think you download the images in tachiyomi format, but add an extra step as to make a zip file per chapter folders. So, "Chapter. 1" folder becomes "Chapter. 1.zip".

I wanted to get that folder in 7-zip compressed file instead of zip-compressed one, like "Chapter. 1.7z". I don't care if it can't be read through any Tachiyomi Readers/Apps.

That is the purpose of my Issue.

**Comment by mansuf** [comment]
mangadex-downloader has always been for offline reading manga. But this is something new, well maybe there is another type of archive formats coming soon (gzip, tar, etc). Who knows 👀

Anyway, thanks for the idea. This will be added in next release as `7z` format. But it may take some time since i'm not familiar with 7z compression (also it use third party library).

**Comment by rokibhasansagar** [comment]
Thanks 😄 

No pressure on this feature. This do need external dependencies to work, so when and if you get familiar with the process, do add it.

In the mean time, I'm downloading as "Tachiyomi" format, then manually compressing every folder to get `.7z` as-well-as `.tar.zst` file using bash script (in remote server of course).

Even if the feature gets rejected (as it may have multiple dependencies which might bloat the program), I can now get a workaround remotely, so no rush there.

**Comment by mansuf** [comment]
Feature added in https://github.com/mansuf/mangadex-downloader/commit/9d625677738ed6be0eded289b8858ec950cba773

You can install dev version if you want to try it early.

**NOTE**: You must install [py7zr](https://pypi.org/project/py7zr/) in order to download with any `cb7` formats
