### ISSUE TITLE
Feature Request: Throttle

### ISSUE THREAD

**Issue by garbled1** [mansuf/mangadex-downloader#24]
Would it be possible to add a throttle option of some kind?  Like a sleep between pages?  I worry that if we hit it too hard eventually they will cloudflare the thing....

**Comment by mansuf** [comment]
The app has rate limit handler, so if you being rate limited by MangaDex, the app will put into sleep until given time. 

See this example output below
```shell
$ mangadex-dl "https://mangadex.org/title/..." --cover none
[INFO] Checking url = https://mangadex.org/title/...
[INFO] Using English language
[INFO] Downloading cover manga ...
[INFO] Fetching all chapters...
[INFO] Using pdf format
[INFO] Getting images from chapter 1
[INFO] We being rate limited, sleeping for 59.27 (attempt: 1) # <--- Delay execution for 59.27 seconds and then continue if done sleeping
...
```

Also, MangaDex is using DDoS-Guard not Cloudflare.

**Comment by garbled1** [comment]
I'm just saying' Id' like to add an additional voluntary rate limit, to avoid any possible future issues.

**Comment by mansuf** [comment]
Done, added in https://github.com/mansuf/mangadex-downloader/commit/c026bf453b387f4788cf842f617d8e12285b7ef4. Thanks for the idea !
