### ISSUE TITLE
Add option to batch download any selectable prompt (library, list, followed-list, etc)

### ISSUE THREAD

**Issue by basilelt** [mansuf/mangadex-downloader#29]
### The idea

Hello, it would be nice to be able to download all the titles from a group by only giving the group id to the downloader instead of having to select those one by one.

Thank you very much for your work :)

### Why this feature should be added to the app ?

It would save a lot of time.

**Comment by mansuf** [comment]
Added to [v2.0.0 development](https://github.com/users/mansuf/projects/3), this feature will be added soon (no ETA, because i have lots of stuff to do).

Anyway, thanks for the idea ✨.

**Comment by basilelt** [comment]
Thank you for your response !

I also just saw that user library download works in the same way (selecting which title I would want to download) and having an option to download them all would also save a lot of time for people wanting to archive their followed titles.

**Comment by mansuf** [comment]
Added in https://github.com/mansuf/mangadex-downloader/pull/25/commits/76d7ab62a14bf822111c899e0a560bfc210bdb9b

You can install development version if you want to try it early.

```shell
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@76d7ab62a14bf822111c899e0a560bfc210bdb9b
```

**Comment by basilelt** [comment]
I thank you so much for that !
Works fine for library and can even check if it's already downloaded.
