### ISSUE TITLE
Add a option to disable creation of chapter info

### ISSUE THREAD

**Issue by Tenpi** [mansuf/mangadex-downloader#30]
### The idea

Why would you add this ugly thing, can you remove it please? I don't see an option to remove them. 

<img width="488" alt="スクリーンショット 2022-09-01 午後7 41 35" src="https://user-images.githubusercontent.com/37512637/188030461-adcfae53-f7ea-4632-a8af-8c434ec3c066.png">

### Why this feature should be added to the app ?

Looks ugly

**Comment by mansuf** [comment]
That "ugly" thing called chapter info, it gives you information what chapter and volume currently you reading on. I assume you download manga in any `volume` or `single` format, so that thing is created.

Is there any reason other than "looks ugly" to remove this thing ?

**Comment by Tenpi** [comment]
> Is there any reason other than "looks ugly" to remove this thing ?

I am looking between fan translations and the japanese manga for studying. However, because you added these chapter covers the downloaded manga is not the same length as the original. It is very annoying to figure out which pages correspond to which. Manually deleting the covers doesn't fix the incorrect page number in the filename eg. `Vol-105.jpg` in the manga downloaded by this program would be `Vol-100.jpg` of the actual manga.

**Comment by mansuf** [comment]
Fair enough, thanks for the explanation 👍.

Added to [v2.0.0 development](https://github.com/users/mansuf/projects/3). There will be option that you can use to disable creation of chapter info for any `volume` and `single` format.

The chapter info will remain exist **as is** (because personally i need them)

**Comment by mansuf** [comment]
Added in https://github.com/mansuf/mangadex-downloader/commit/7dc5b2cd097896c29520b5c9858dbb5bc64bd9c9

You can install development version if you want to try it early.

```shell
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@7dc5b2cd097896c29520b5c9858dbb5bc64bd9c9
```

You can use it from `--no-chapter-info` option

```shell
mangadex-dl "insert URL here" --no-chapter-info
```

**Comment by Tenpi** [comment]
Thanks a lot!
