### ISSUE TITLE
Add `--no-group-name` to config

### ISSUE THREAD

**Issue by HighOnBuffs** [mansuf/mangadex-downloader#31]
### The idea

It would be very nice to have a config file inside the main folder, so i can just set --save-as cbz and --path "" and especially --no-group-name so i dont have to write it every time i download something.

### Why this feature should be added to the app ?

It would greatly ease the usability.

**Comment by HighOnBuffs** [comment]
Also a way to rename all chapters to just chapter 1....2.....3....etc and not have the uploader name so its out of order!

**Comment by mansuf** [comment]
Do you mean this https://mangadex-dl.mansuf.link/en/stable/cli_usage/advanced.html#configuration ?

**Comment by HighOnBuffs** [comment]
> Do you mean this https://mangadex-dl.mansuf.link/en/stable/cli_usage/advanced.html#configuration ?

Yes it hurts to be blind sometimes... :^)

**Comment by mansuf** [comment]
> Also a way to rename all chapters to just chapter 1....2.....3....etc and not have the uploader name so its out of order!

The app also have that feature (`--no-group-name`), but not available for config.

https://mangadex-dl.mansuf.link/en/stable/cli_ref/index.html#cmdoption-no-group-name

**Comment by HighOnBuffs** [comment]
> > Also a way to rename all chapters to just chapter 1....2.....3....etc and not have the uploader name so its out of order!
> 
> The app also have that feature (`--no-group-name`), but not available for config.
> 
> https://mangadex-dl.mansuf.link/en/stable/cli_ref/index.html#cmdoption-no-group-name

Awesome but i would be great if that could be added to the config!

**Comment by mansuf** [comment]
Sure :)

Added to [v2.0.0 development](https://github.com/users/mansuf/projects/3).

**Comment by HighOnBuffs** [comment]
Awesome! Thanks for the stellar work :)

**Comment by mansuf** [comment]
Added in https://github.com/mansuf/mangadex-downloader/commit/e94d9911f0037445c7ef95fe4cc3c10cb2433a71

You can install development version if you want to try it early.

```shell
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@e94d9911f0037445c7ef95fe4cc3c10cb2433a71
```

Usage

```shell
# Set config `no_group_name` to True
mangadex-dl "conf:no_group_name=1"
```
