### ISSUE TITLE
Add search filter for rating

### ISSUE THREAD

**Issue by HighOnBuffs** [mansuf/mangadex-downloader#32]
### The idea

So you could just search for certain year and highest rating and download the first 3 chapters from all those manga to then test read what you like to read further all from your CLI :)

Maybe the workflow could be like: mangadex-dl -s -sf "year=2022" -sf "rating=8-10" then the first 100 are presented in descending rating and you can say download the first 1-3 chapters from the first 10-100 manga from best rated to worst.

That would be brilliant for quickly finding new manga and test them.

### Why this feature should be added to the app ?

Greatly enhances workflow of finding new manga to read.

**Comment by mansuf** [comment]
Search filter like `-sf "rating=8-10"` are not yet supported by MangaDex itself. It only support "Sort by" filter (from highest ratings to lowest ratings, vice versa). It is possible to do this filter manually in the app, but it's time consuming and probably get rate limited many times before showing the results

**Comment by HighOnBuffs** [comment]
> 

Too bad. Still thanks for the amazing work! What is the exact parameter for "sort by ranking"?

**Comment by mansuf** [comment]
> What is the exact parameter for "sort by ranking"?

The app doesn't have it right now (it only exist in frontend website), because in API documentation (https://api.mangadex.org/docs/swagger.html#/Manga/get-search-manga) filter "order by ratings" are not exist for some reason. And if i want to implemented it now, it would cause break the whole search feature. Because that thing can be changed anytime without any notice

**Comment by mansuf** [comment]
Reopen, i was not looking in API main documentation page (sorry about that). And yes, filter "order by ratings" are exist in API documentation.

Added to [v2.0.0 development](https://github.com/users/mansuf/projects/3)

**Comment by mansuf** [comment]
Added in https://github.com/mansuf/mangadex-downloader/pull/25/commits/b801d685e6171e28b24711c1ce8efc0550b37f65

You can install development version if you want to try it early.

```shell
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@b801d685e6171e28b24711c1ce8efc0550b37f65
```

Usage

```shell
# Search with "Highest rating" order
mangadex-dl -s -sf "order[rating]=desc"
```

For more info about all `order[...]` search filters, you can [see here](https://mangadex-dl.mansuf.link/en/v2.0.0/cli_ref/search_filters.html#cmdoption-arg-order-title)
