### ISSUE TITLE
Bug on download for v2 beta

### ISSUE THREAD

**Issue by basilelt** [mansuf/mangadex-downloader#34]
### What happened ?

Download bug and come to an alt after some time. I guess this is a bug on mangadex-downloader as the size of the image is way too big to be the true size but could come from mangadex.
![image](https://user-images.githubusercontent.com/66386196/189841561-502d985d-a7ba-4225-a6c5-2d2753325ead.png)

### What did you expect to happen ?

The image to be a smaller size and after a few retry to download correctly

### App version

2.0.0

### Installation origin

PyPI (Python Package Index)

### Reproducible command

``mangadex-downloader "library" --input-pos "*" --use-chapter-title --login --login-username "*******" --login-password "********" --cover "original" --delay-requests 1.5 --save-as raw --path "D:\Manga\mangadex"``

**Comment by mansuf** [comment]
I assume that your download has been interrupted (either your connection problem or MangaDex servers problem), and the app is trying to resume the download.

There is a bug in MangaDex right now after their migrating the servers. Which caused resume download process broken.

I suggest you to not login right now and your download should working fine even if it's trying to resume download.

**Comment by mansuf** [comment]
This should be fixed in https://github.com/mansuf/mangadex-downloader/commit/ed1658650f840bfdc4d257e086c9bf2147eae8b0

You can try reinstall the development version

```shell
pip install git+https://github.com/mansuf/mangadex-downloader.git@ed1658650f840bfdc4d257e086c9bf2147eae8b0
```

You can reopen this issue if error like that happened again

**Comment by basilelt** [comment]
Thanks a lot, will test :)
