### ISSUE TITLE
Only Download Newest Chapters

### ISSUE THREAD

**Issue by Kalidibus** [mansuf/mangadex-downloader#38]
Is there a flag that will allow us to only download the newest "n" chapters? 

I would like to run this script automatically once a week, and download the newest, say 5, chapters from each release I'm following. Right now I only see how to download a set number range which wouldn't work as you need to know the chapter number and change it each time.

**Comment by Kalidibus** [comment]
Main point of this would be to avoid hitting every file on a large series each time, otherwise I'd just run it open

**Comment by mansuf** [comment]
> Main point of this would be to avoid hitting every file on a large series each time, otherwise I'd just run it open

Did you mean, avoid "checking every file if it's exist or not " ?

i'm pretty sure the application can check if the chapters is exist or not, if exists then it would be simply skipped (unless you're using `raw` format, it would be verify each images and has higher chance to get rate limited).

**Comment by Kalidibus** [comment]
> > Main point of this would be to avoid hitting every file on a large series each time, otherwise I'd just run it open
> 
> Did you mean, avoid "checking every file if it's exist or not " ?
> 
> i'm pretty sure the application can check if the chapters is exist or not, if exists then it would be simply skipped (unless you're using `raw` format, it would be verify each images and has higher chance to get rate limited).

Sorry, you're correct. I think i was on an old version that checked each file, but since updating it only checks that the volume is downloaded so all good.
