### ISSUE TITLE
other chapter-cover options when using save-as cbz-volume

### ISSUE THREAD

**Issue by benpoe** [mansuf/mangadex-downloader#40]
Maybe I haven't seen it, but are there more options on chapter-cover creation (esp when save as cbz-volume is used?)

the current chaptertitle+cover is in landscape and mess up my pretty library

<img width="1015" alt="Screenshot 2022-12-28 at 12 04 37" src="https://user-images.githubusercontent.com/27544560/209802988-243f3fab-7c2e-4f93-9ca4-07d16ebcbf22.png">

more control on how the covers are generated would be nice (i'd just opt for the title in the cover itself, maybe with some transparant black bakground for readability)

**Comment by mansuf** [comment]
The app doesn't have control over generated chapter covers as it's generated by MangaDex itself. It was actually used as embed for MangaDex website. 

Before v2.0.0, the app has self-generated chapter covers, but i was told that it was ugly (see #30). The chapter covers was generated using [Pillow](https://github.com/python-pillow/Pillow) library. And when developing v2.0.0 it was decided by me to change it from self-generated to MangaDex generated instead as it's more clear, sadly it was landscape image not portrait (see patch [`be86d1a`](https://github.com/mansuf/mangadex-downloader/commit/be86d1a06e23480e692226d5786345820e8d1875#diff-e5dfe3c1008a55e4a1e1cf8350e62898d8bca9db0bee6ab2f679d983e328742e) for `format/utils.py` )

There is a problem using self-generated chapter. People were getting errors when specified font is not found in Linux-based OS. So it's up to them using shipped font or recommended one ( see #20 )

**Comment by mansuf** [comment]
FYI: You can turn off these chapter cover creation by using `--no-chapter-info`

**Comment by kmfstudio** [comment]
> The app doesn't have control over generated chapter covers as it's generated by MangaDex itself. It was actually used as embed for MangaDex website.
> 
> Before v2.0.0, the app has self-generated chapter covers, but i was told that it was ugly (see #30). The chapter covers was generated using [Pillow](https://github.com/python-pillow/Pillow) library. And when developing v2.0.0 it was decided by me to change it from self-generated to MangaDex generated instead as it's more clear, sadly it was landscape image not portrait (see patch [`be86d1a`](https://github.com/mansuf/mangadex-downloader/commit/be86d1a06e23480e692226d5786345820e8d1875#diff-e5dfe3c1008a55e4a1e1cf8350e62898d8bca9db0bee6ab2f679d983e328742e) for `format/utils.py` )
> 
> There is a problem using self-generated chapter cover. People were getting errors when specified font is not found in Linux-based OS. So it's up to them using shipped font or recommended one ( see #20 )


ok. i didn't realize it's a "mangadex"-chapter cover...

I still want the capter title though.
however, is it possible to have the cover added to the beginning of the cbz-volume then BEFORE the title? it'd achieve the same result (IE, nice thumbnails) and i'd be happy

**Comment by mansuf** [comment]
How about this ? this is basically cropped version of MangaDex chapter cover. Try to put in your media server as a cover.
If it's good, maybe i will consider to change it.

![image](https://user-images.githubusercontent.com/43638783/210038996-cc5861e6-e45b-4f19-9209-9c26e8daac4c.png)

**Comment by kmfstudio** [comment]
> How about this ? this is basically cropped version of MangaDex chapter cover. Try to put in your media server as a cover. If it's good, maybe i will consider to change it.
> 
> ![image](https://user-images.githubusercontent.com/43638783/210038996-cc5861e6-e45b-4f19-9209-9c26e8daac4c.png)


hmm.. no, that'd be just a bunch of black blobs in the reader, so it's even worse. i find this a better solution:
>is it possible to have the cover added to the beginning of the cbz-volume then BEFORE the title? it'd achieve the same  result (IE, nice thumbnails) 
as the cover is already downloaded, it'd be easy just to copy them as the first file of a volume.

**Comment by mansuf** [comment]
This issue is closed as it's clear that is no option to control creation of chapter-cover (because it's generated by MangaDex, see https://github.com/mansuf/mangadex-downloader/issues/40#issuecomment-1366601996).

> is it possible to have the cover added to the beginning of the cbz-volume then BEFORE the title? it'd achieve the same result (IE, nice thumbnails)

As for this, i have created issue #41 to discuss adding volume cover for any `volume` formats
