### ISSUE TITLE
Add optional volume cover for any `volume` formats

### ISSUE THREAD

**Issue by mansuf** [mansuf/mangadex-downloader#41]
There is list of cover representing each volumes in MangaDex.

![image](https://user-images.githubusercontent.com/43638783/210942641-65d3a2d5-68ac-4b59-b1ba-22d8fb17606b.png)

Maybe we can use that in first page in any `volume` formats, instead of placing [chapter info (or cover)](https://mangadex-dl.mansuf.link/en/stable/cli_ref/chapter_info.html) in first page.

However, the chapter cover (info) is still can be added after volume cover. But, it's gonna be changed to optional feature (default to be disabled). So `--no-chapter-info` will get deprecated and wil be replaced with `--use-chapter-cover` instead.

Also add option to enable creation volume cover (`--use-volume-cover` / `-uvc`)

**Comment by benpoe** [comment]
may be nice to specify that the chapter info should still be used to depict chapters in a volume, so it's the volume cover And chapter info for each chapter to get the best volumes possible

**Comment by mansuf** [comment]
> may be nice to specify that the chapter info should still be used to depict chapters in a volume, so it's the volume cover And chapter info for each chapter to get the best volumes possible

iirc, the pages order should be like this right ?

```
volume cover -> chapter cover (info) 1 -> main chapter 1 -> chapter cover (info) 2 -> main chapter 2 -> etc...
```

**Comment by catouberos** [comment]
This would be perfect to be used when downloading as, for example, `.cbz` to be copy on to an e-reader, or even some reader app on various platform. The volume cover would be more representing and fitted as they're in vertical in my opinion, and easier to distinguish from other volumes.

**Comment by mansuf** [comment]
> Another suggestion would be to also change the cover inside the "chapter cover (info)" (right side) to the respective volume cover.

@NidokingMaster See https://github.com/mansuf/mangadex-downloader/issues/40#issuecomment-1366601996

**Comment by kmfstudio** [comment]
> > Another suggestion would be to also change the cover inside the "chapter cover (info)" (right side) to the respective volume cover.
> 
> @NidokingMaster See [#40 (comment)](https://github.com/mansuf/mangadex-downloader/issues/40#issuecomment-1366601996)

I'm not too familiar with the image manupilation possibilities of python, but isn't it a simple "duplicate image, crop out chapter info/ chapter cover and save ?" It's a simple manupilation with PHP 10 years ago, with python this must be simplier.

of course,  it might not be worth the investment in time.

**Comment by mansuf** [comment]
> but isn't it a simple "duplicate image, crop out chapter info/ chapter cover and save ?" It's a simple manupilation with PHP 10 years ago, with python this must be simplier.

Yes it is simple, but the blurred background still containing old volume cover not the new one. I have tried this in my test code 

```python
import requests
from PIL import Image

# NOTE: 0 means from the beginning

width_cropped_ch_info = 757
height_cropped_ch_info = 630
ch_info_res = (1200, 630)
vol_cover_new_size = (ch_info_res[0] - width_cropped_ch_info, height_cropped_ch_info)

# See https://pillow.readthedocs.io/en/stable/handbook/concepts.html#coordinate-system
coordinate_crop_ch_info = (0, 0, width_cropped_ch_info, height_cropped_ch_info)

# Get the chapter info
# https://mangadex.org/title/eb48c615-1c00-4726-b839-850d01d774b0/you-weren-t-my-sister-but-my-fianc-e
r = requests.get("https://og.mangadex.org/og-image/chapter/6b8cea19-30db-44cd-8486-06d1fce881fe", stream=True)

ch_info_orig = Image.open(r.raw)

# Remove the old cover
ch_info_orig = ch_info_orig.crop(coordinate_crop_ch_info)

# Make new blank image (1200, 630) and paste the chapter info to new image
ch_info = Image.new("RGB", ch_info_res)
ch_info.paste(ch_info_orig)

# Get the new volume cover
# https://mangadex.org/title/0bd72573-7512-4a38-b9fe-ae00a4776fdd/amarimono-isekaijin-no-jiyuu-seikatsu-yuusha-ja-nai-node-katteni-yarasete-moraimasu
r = requests.get("https://mangadex.org/covers/0bd72573-7512-4a38-b9fe-ae00a4776fdd/9aab4ff4-68da-4a74-8036-987a1f69d6b8.jpg", stream=True)

vol_cover = Image.open(r.raw)

# Resize it first to make it fit in chapter info
new_vol_cover = vol_cover.resize(vol_cover_new_size)

# Then paste the new volume cover to chapter info
ch_info.paste(new_vol_cover, box=(width_cropped_ch_info, 0))

# Save it
ch_info.save("ch_info.png")
```

The result:

![ch_info](https://user-images.githubusercontent.com/43638783/215343388-a1bf5285-ba12-436d-90fc-177e68d79558.png)

**Comment by mansuf** [comment]
> Another approach would be to let python generate a new chapter info from the downloaded volume cover. I think mansuf had a similar idea but there were problems with linux and fonts.

Indeed, a lot of users have trouble to generate chapter info due to missing fonts. Maybe shipping a font can be fixed, but i need a font that has open source license. Arial font is proprietary license, so i cannot ship them.

Another problem for using self-generated chapter info is "out-of-frame text" problem in Pillow module. Of course it can be dynamically resized the fonts with this answer -> https://stackoverflow.com/questions/41528576/how-can-i-write-text-on-an-image-and-not-go-outside-of-the-border.

Using @NidokingMaster idea might be a good thing, but it takes a lot of efforts and time. I don't have full time to work on this project due to college. And there is tons of stuffs that has not been finished in this project yet.

**Comment by benpoe** [comment]
> > Another approach would be to let python generate a new chapter info from the downloaded volume cover. I think mansuf had a similar idea but there were problems with linux and fonts.
> 
> Indeed, a lot of users have trouble to generate chapter info due to missing fonts. Maybe shipping a font can be fixed, but i need a font that has open source license. Arial font is proprietary license, so i cannot ship them.
> 
> Another problem for using self-generated chapter info is "out-of-frame text" problem in Pillow module. Of course it can be dynamically resized the fonts with this answer -> https://stackoverflow.com/questions/41528576/how-can-i-write-text-on-an-image-and-not-go-outside-of-the-border.
> 
> Using @NidokingMaster idea might be a good thing, but it takes a lot of efforts and time. I don't have full time to work on this project due to college. And there is tons of stuffs that has not been finished in this project yet.

I'd suggest to add @NidokingMaster as a feature which might or might not be implemented in the future and just do what you have suggested yourself with the ordering of covers/chapter info which would good enough to close this very issue.

**Comment by mansuf** [comment]
Optional volume cover feature has been added in https://github.com/mansuf/mangadex-downloader/commit/e3f6ac0cbe530d7c8947419a298600afe78354df

These feature can be installed in development version

```
pip install git+https://github.com/mansuf/mangadex-downloader.git@e3f6ac0cbe530d7c8947419a298600afe78354df
```

And it can be accessed with `--use-volume-cover`

```sh
mangadex-dl "https://mangadex.org/title/4265c437-7d57-4d31-9b1d-0e574a07b7b7" --use-volume-cover
```

As for chapter cover (info) it will be changed as optional feature, which means it is disabled by default, so you must enable it with `--use-chapter-cover`

```
mangadex-dl "https://mangadex.org/title/4265c437-7d57-4d31-9b1d-0e574a07b7b7" --use-volume-cover --use-chapter-cover
```

**Comment by mansuf** [comment]
For "New chapter info (cover)" idea, it will be discussed in https://github.com/mansuf/mangadex-downloader/issues/44
