### ISSUE TITLE
Add ability to disable tracking downloads

### ISSUE THREAD

**Issue by ScherisMarie** [mansuf/mangadex-downloader#45]
On _macOS_, I have a custom **Shortcuts** script for automating downloads using the link stored in the clipboard. It's really just a quick GUI to run shell scripts commands, though.

<img width="623" alt="Screenshot 2023-02-04 at 2 57 10 AM" src="https://user-images.githubusercontent.com/35884882/216756091-a4f84c20-e672-4c59-9385-ff2db76a41cb.png">

I just updated to v2.6.1 (was on v2.5.x's December release prior), and it seems single & batch commands are creating a **downloaded-raw.json** file inside the manga's folder.

Is this intentional? (If so, is there a flag to not have it generate it?)

**Comment by mansuf** [comment]
Yes, it was part of commit https://github.com/mansuf/mangadex-downloader/commit/865b7f5988a9cd92e21112ac8649a29299b5023f. The file will track downloaded chapters and images. So next time you run the application, it will only download missing, corrupted or new chapters and images. This is just to prevent get rate-limited frequently by MangaDex API as users want to download latest chapters only.

Currently, it does not have option to deactivate it. But i can make it if you want to.

**Comment by mansuf** [comment]
Oh another note (since you setup the script activated with clipboard). You should not copying MangaDex forums thread URL. Starting v2.6.0, the application can download from forums thread (`https://forums.mangadex.org/threads/...`). It will try to find MangaDex URLs found in the forums thread. 

The app will left hanging out as it asking you to choose which manga, chapter, or list you want to download (unless you're using `--input-pos`).

Maybe it's convenient to you or maybe not, but i'm trying to warning you.

**Comment by ScherisMarie** [comment]
I only feed it the exact chapter URL or the title URL (and I have it prompt for the specific start & end chapters range), so I think that should be alright?

**Comment by mansuf** [comment]
> I only feed it the exact chapter URL or the title URL (and I have it prompt for the specific start & end chapters range), so I think that should be alright?

Yes, it's okay.

**Comment by benpoe** [comment]
> Yes, it was part of commit [865b7f5](https://github.com/mansuf/mangadex-downloader/commit/865b7f5988a9cd92e21112ac8649a29299b5023f). The file will track downloaded chapters and images. So next time you run the application, it will only download missing, corrupted or new chapters and images. This is just to prevent get rate-limited frequently by MangaDex API as users want to download latest chapters only.
> 
> Currently, it does not have option to deactivate it. But i can make it if you want to.

can the original url also be included in the json file? it'd help to create a job to redownload new chapters

**Comment by mansuf** [comment]
Added in https://github.com/mansuf/mangadex-downloader/pull/49/commits/3952bc6b72c5eb116e02ee38714ec8c64e99b70a

You can use `--no-track` option and file `downloaded-{format}.json` will be gone

```sh
$ mangadex-dl "https://mangadex.org/title/..." --no-track -f cbz
```
