### ISSUE TITLE
Only the cover and the download.db are downloaded

### ISSUE THREAD

**Issue by jorgeperezlara** [mansuf/mangadex-downloader#55]
### What happened ?

I run this on Fedora 37, on the stock Python3 package (version Python 3.11.2).

When trying to download a manga (so far I've tried Uzumaki and The Decagon House Murders, having similar results for both) I'm unable to download anything appart from the cover art and the download.db file.

I'm using the commands below:
```
https://mangadex.org/title/f4cfbb1c-766e-49db-ae80-1a5db3cbcc1b/uzumaki
https://mangadex.org/title/0c0b19c8-efde-4a65-b98a-9c7fc79fd173/the-decagon-house-murders
```

I am not able to do anything to get the full manga. Am I doing something wrong or is there an issue with the package? According to the docs, what I'm typing should work ok.

BTW thank you for this fantastic tool!

### What did you expect to happen ?

To download the full manga.

### OS version

Fedora 37, Python3 version 3.11.2

### App version

mangadex-downloader v2.8.1 (https://github.com/mansuf/mangadex-downloader)
Python: 3.11.2
arch: x64
bundled executable: no

### Installation origin

PyPI (Python Package Index)

### Reproducible command

https://mangadex.org/title/f4cfbb1c-766e-49db-ae80-1a5db3cbcc1b/uzumaki
https://mangadex.org/title/0c0b19c8-efde-4a65-b98a-9c7fc79fd173/the-decagon-house-murders

**Comment by mansuf** [comment]
The translated chapters in some language that you're looking for is not found on MangaDex. The application didn't show error chapters not found, maybe i will fix that later.

I tested in english language, it's empty

```
D:\>mangadex-dl "https://mangadex.org/title/f4cfbb1c-766e-49db-ae80-1a5db3cbcc1b/uzumaki"
[INFO] Checking url = https://mangadex.org/title/f4cfbb1c-766e-49db-ae80-1a5db3cbcc1b/uzumaki
[INFO] Using English language
[INFO] Fetching all chapters...
[INFO] Downloading cover manga Uzumaki
file_sizes: 100%|██████████████████████████| 1.64M/1.64M [00:00<00:00, 9.34MB/s]
[INFO] Download directory is set to "D:\Manga\test_manga\Uzumaki"
[INFO] Using pdf format
[INFO] Preparing to download...
[INFO] Waiting for chapter read marker to finish
[INFO] Download finished for manga "Uzumaki"
[INFO] Cleaning up...
```

Try using different language. By default, the application is configured using English language. You can use `--language` option to use another language

https://mangadex-dl.mansuf.link/en/stable/cli_usage/index.html#download-manga-chapter-or-list-in-different-translated-language

**Comment by jorgeperezlara** [comment]
You're right, I didn't notice that. It's a shame and I'm surprised there are so many languages, but no English translation.
