### ISSUE TITLE
Cannot download from user library and its filter "library:reading" when -s --input-pos argument added

### ISSUE THREAD

**Issue by sandycorzeta** [mansuf/mangadex-downloader#58]
### What happened ?

I want to download all of my user library from my mangadex account without having any selection interaction first. Sadly i cannot using it with the `library:reading` or `library:plan_to_read` when i add the `-s --input-pos="*"` argument. The error says `Error: Manga search results for "library:reading" are empty`. I can use just the `library` but its not downloading my user library, but instead downloading random manga that contain word library in it.

### What did you expect to happen ?

I can download the manga from my mangadex user library account without having imposed to select which manga first.

### OS version

DietPi (Debian Buster) on Raspberry Pi 3B

### App version

2.8.3

### Installation origin

PyPI (Python Package Index)

### Reproducible command

`mangadex-dl 'library:reading' --login --login-username ***** --login-password ****** -s --input-pos "*"`

**Comment by mansuf** [comment]
For your information, `-s` or `--search` option is for searching mode. So any command or url that you put in there become query to MangaDex search.

While `--input-pos` is to automatically select choices without getting prompted and value `*` is to select all choices. 

https://mangadex-dl.mansuf.link/en/stable/cli_ref/index.html#search-related
https://mangadex-dl.mansuf.link/en/stable/cli_ref/index.html#cmdoption-input-pos
