### ISSUE TITLE
Ability to download covers only

### ISSUE THREAD

**Issue by anonymous5555522222** [mansuf/mangadex-downloader#60]
### The idea

Firstly, thank you very, very much for making this software. It makes the task to archive manga easy.
However, it seems to be missing a feature, which is to solely download all covers that were uploaded to the "Art" section.
My suggestion is to add a switch called "--download-all-covers" or "--only-download-covers" which will download every image from that section. I tried to figure it out by using existing options such as "--use-volume-cover", to no avail. Would be great if the "--cover" switch would work with "--download-all-covers" as well, to select the resolution of the covers.

### Why this feature should be added to the app ?

With this feature, users wouldn't need to stress MangaDex's servers, neither waste their bandwidth.
Thank you.

**Comment by mansuf** [comment]
> With this feature, users wouldn't need to stress MangaDex's servers, neither waste their bandwidth.

Can you explain more about this ? 
Technically downloading all covers will cost a lot of bandwidth than downloading a single cover. 

I understand about the feature you requested. But the reason you want them is confusing to me.

**Comment by anonymous5555522222** [comment]
> > With this feature, users wouldn't need to stress MangaDex's servers, neither waste their bandwidth.
> 
> Can you explain more about this ? Technically downloading all covers will cost a lot of bandwidth than downloading a single cover.
> 
> I understand about the feature you requested. But the reason you want them is confusing to me.

I'm sorry. What I meant is that with this option, the user would not need to download every chapter uploaded and search for the cover images, if they were uploaded at all by the scanlation group inside the first chapter of each volume.

The reason for me needing this is silly, it's mostly because I like to do charts and documents with images of manga I have completed. With this option, I could download all covers and pick the best looking one(s), with consistent resolution (256px or 512px) without having to visit MangaDex.

Thanks in advance.

**Comment by mansuf** [comment]
I have made PR #61 about this, you can try to install and use it.

**NOTE**: You must have Python 3.8.x or up with pip and git installed on your device.

```
pip install git+https://github.com/mansuf/mangadex-downloader.git@5011fe3d30e2d36b9e0c7329532ebc2a9000415d
```

---------

> My suggestion is to add a switch called "--download-all-covers" or "--only-download-covers" which will download every image from that section

Instead of using `--download-all-covers` or `--only-download-covers`, i've made command `cover` to show list of covers. You can choose it which cover you want to download. This command will download the covers only.

```shell
# Manga id only
mangadex-dl "cover:f9c33607-9180-4ba6-b85c-e4b5faee7192"

# Full manga URL
mangadex-dl "cover:https://mangadex.org/title/f9c33607-9180-4ba6-b85c-e4b5faee7192"

# Full cover manga URL
mangadex-dl "cover:https://mangadex.org/covers/f9c33607-9180-4ba6-b85c-e4b5faee7192/c18da525-e34f-4128-a696-4477b6ce6827.png"
```

If you don't wanna get prompted use `--input-pos` option.

```sh
# Automatically select choice 1 
mangadex-dl "cover:https://mangadex.org/title/..." --input-pos 1 

# Automatically select all choices
mangadex-dl "cover:https://mangadex.org/title/..." --input-pos "*"
```

> Would be great if the "--cover" switch would work with "--download-all-covers" as well, to select the resolution of the covers.

As for this, you can use different command such as `cover-512px` or `cover-256px` to choose different quality.

```sh
# 512px quality
mangadex-dl "cover-512px:https://mangadex.org/title/f9c33607-9180-4ba6-b85c-e4b5faee7192"

# 256px quality
mangadex-dl "cover-256px:https://mangadex.org/title/f9c33607-9180-4ba6-b85c-e4b5faee7192"
```

**Comment by anonymous5555522222** [comment]
> I have made PR #61 about this, you can try to install and use it.
> 
> **NOTE**: You must have Python 3.8.x or up with pip and git installed on your device.
> 
> ```
> pip uninstall mangadex-downloader
> pip install git+https://github.com/mansuf/mangadex-downloader.git@5011fe3d30e2d36b9e0c7329532ebc2a9000415d
> ```
> 
> Let me know when you have issues with this new feature 🙂
> 
> > My suggestion is to add a switch called "--download-all-covers" or "--only-download-covers" which will download every image from that section
> 
> Instead of using `--download-all-covers` or `--only-download-covers`, i've made command `cover` to show list of covers. You can choose it which cover you want to download. This command will download the covers only.
> 
> ```shell
> # Manga id only
> mangadex-dl "cover:f9c33607-9180-4ba6-b85c-e4b5faee7192"
> 
> # Full manga URL
> mangadex-dl "cover:https://mangadex.org/title/f9c33607-9180-4ba6-b85c-e4b5faee7192"
> 
> # Full cover manga URL
> mangadex-dl "cover:https://mangadex.org/covers/f9c33607-9180-4ba6-b85c-e4b5faee7192/c18da525-e34f-4128-a696-4477b6ce6827.png"
> ```
> 
> If you don't wanna get prompted use `--input-pos` option.
> 
> ```shell
> # Automatically select choice 1 
> mangadex-dl "cover:https://mangadex.org/title/..." --input-pos 1 
> 
> # Automatically select all choices
> mangadex-dl "cover:https://mangadex.org/title/..." --input-pos "*"
> ```
> 
> > Would be great if the "--cover" switch would work with "--download-all-covers" as well, to select the resolution of the covers.
> 
> As for this, you can use different command such as `cover-512px` or `cover-256px` to choose different quality.
> 
> ```shell
> # 512px quality
> mangadex-dl "cover-512px:https://mangadex.org/title/f9c33607-9180-4ba6-b85c-e4b5faee7192"
> 
> # 256px quality
> mangadex-dl "cover-256px:https://mangadex.org/title/f9c33607-9180-4ba6-b85c-e4b5faee7192"
> ```
> 
> I forgot to mention, you can download manga covers directly to the app. Just give the URL and you're good to go.
> 
> ```shell
> mangadex-dl "https://mangadex.org/covers/f9c33607-9180-4ba6-b85c-e4b5faee7192/c18da525-e34f-4128-a696-4477b6ce6827.png"
> ```

Thank you so, so much!
It's working perfectly... There's just something small missing, which is, getting the ID of a manga entry without visiting MangaDex. I managed to find a hacky way to get it though, with this command:
`mangadex-dl --search "manga title" -sc 9999999 --path "X:\"`
In my computer, the X: drive does not exist, so MangaDexDownloader just crashes. However, before crashing, it outputs the ID of the manga entry that I select from the search results! Therefore, this already works good enough for me, but the ability to download covers of a manga entry directly with the search function would be a nice addition.
Again, thank you SO much for this! It's lifesaving for me.
