### ISSUE TITLE
Tachiyomi info missing if using format-volume/single

### ISSUE THREAD

**Issue by fluffyloopy** [mansuf/mangadex-downloader#63]
### What happened ?

details.json doesnt get downloaded if im using --save-as format-volume/single. works if im saving as format without volume/single.

### What did you expect to happen ?

download details.json

### OS version

Windows 10 20H2

### App version

mangadex-downloader v2.9.0 (https://github.com/mansuf/mangadex-downloader)
Python: 3.10.11        
arch: x64
bundled executable: yes

### Installation origin

Github releases

### Reproducible command

mangadex-dl.exe --save-as "cbz-volume" --write-tachiyomi-info --use-volume-cover "https://mangadex.org/title/897959ff-cc94-4627-a9c5-ac13af5ba89f/reversible"

**Comment by mansuf** [comment]
I've made a PR #64 about this, you can try install patched version and test it.

You can get patched version in here (under "artifacts" section):

https://github.com/mansuf/mangadex-downloader/actions/runs/4988492554
