### ISSUE TITLE
[FEATURE] Logging and Progress Bar

### ISSUE THREAD

**Issue by picnixz** [mansuf/mangadex-downloader#65]
### The idea

I would like to suggest reducing the number of logging messages and progress bars by replacing them by up stacked progression bars. More precisely,

- Only print relevant messages on the console e.g., when starting a download or when a chapter / volume / part is completed depending on the merging procedure. For instance, when saving the output as `cbz-volume`, I am only interested when the whole is done and not when each page of each chapter is done. Such messages should be logged in DEBUG mode only.

- By default, the logging verbosity should be rather WARNING than INFO, or it should be possible to suppress info messages. I haven't looked at the source code itself, but is there a way to configure the logger (if it is actually a logger) using an environment variable?

- For progression bars, since `tqdm` supports stacked bars, it would be easier and cleaner to have a progression bar for the 1) volume (progression over the chapters), 2) the chapter volume (progression over the pages) and 3) the page download as it is currently. It should be possible to only show the volume progression or the volume + chapter or all bars. 

I'll be happy to contribute to that but I'll need to dive into the code beforehand. 
 

### Why this feature should be added to the app ?

Having too many messages makes the terminal output quite unreadable. I have no idea about the ETA and I also have no idea which manga I am currently downloading if I am using the `file:URL` syntax.

**Comment by mansuf** [comment]
> For progression bars, since tqdm supports stacked bars, it would be easier and cleaner to have a progression bar for the 1) volume (progression over the chapters), 2) the chapter volume (progression over the pages) and 3) the page download as it is currently. It should be possible to only show the volume progression or the volume + chapter or all bars.

Since it's stacked progress bars, the application should not have other outputs to the console while the progress bars is exist. So you cannot see soft errors or warnings while it's downloading (because the console could be messy). 

Example of soft errors:

- `"xxx" is not valid MangaDex URL`
- `Manga "xxx" has no *some language* chapters`

You may notice these soft errors when you're using batch download.

So, are you okay with this design ?
I don't have a problem for `reduced logger output` part. I just have to add option to change logger level.

**Comment by mansuf** [comment]
From your idea about stacked progress bar, the output should be like this (Correct me if i'm wrong):

```
*Some logger output before starting to download manga*

Pages progress bar
Chapters progress bar
Volume progress bar

# Next manga

*Some logger output before starting to download manga*

Pages progress bar
Chapters progress bar
Volume progress bar
```

Or if you want to show progress bar only (but stacked), i can make it at least 5 total progress bars

- Pages
- Chapters
- Volume
- Manga downloaded (if you're downloading MangaDexList)
- Link processed (if you're using batch download)

**Comment by picnixz** [comment]
> From your idea about stacked progress bar, the output should be like this (Correct me if i'm wrong):

Yes that's what I thought about. In addition, error messages can technically be shown before the progress bar using ANSI escape codes (not sure if it is well supported on Win32 systems though). This can be done by clearing the progression bar, printing the error, and re-rerendering normally. In general errors should not happen much also.

**Comment by picnixz** [comment]
Thanks a lot ! I'll review your PR when I have a bit of time (if you don't mind waiting a bit)
