### ISSUE TITLE
Ignore one shot when using --start-chapter above 0

### ISSUE THREAD

**Issue by KyleErhabor** [mansuf/mangadex-downloader#69]
### The idea

I think one shot chapters (which are usually numbered 0) should be ignored when using the `--start-chapter` flag with a number above 0.

### Why this feature should be added to the app ?

I like to download manga chapters based on what I need, so when I downloaded [The Summer Hikaru Died](https://mangadex.org/title/9e954c6b-7a02-4fd7-986d-6331c0ba95d4/hikaru-ga-shinda-natsu)'s chapter 16, I was surprised that it chose to download the one shot as well, despite using `--start-chapter 16`. Using `--no-oneshot-chapter` to not download the one shot solves this, but I think it would make more sense to treat the one shot as its own regular chapter, so when using `--start-chapter`, there's no need to worry/check if there's a one shot as well.

**Comment by mansuf** [comment]
Usually, in manga there is 
- prologue chapter
- main chapter
- oneshot chapter

What i'm thinking is oneshot are separated story from main chapters and prologue chapters. So it's kinda make sense for me to make `--no-oneshot-chapter` option.

And sometimes, oneshot chapter in MangaDex API are showing `null` chapter that the range filter (`--start-chapter` and `--end-chapter`) aren't working.

If you don't want to use `--no-oneshot-chapter`, i can make it available in configs, so you don't have to type option `--no-oneshot-chapter` everytime you wanna download a manga.
