### ISSUE TITLE
Add option to ignore missing chapters

### ISSUE THREAD

**Issue by mr-brune** [mansuf/mangadex-downloader#70]
### The idea

When i downlaod some chapter from a tilte after i read them i woud like to remove it from the folder and dont download those chapter anymore but the program gives me error and it downlaod the chapter again. I would like the option to not check if the chapter where deleted

### Why this feature should be added to the app ?

i would like to create a script that download only a new chapter to convert these for my kindle but it keeps downloading old chapters

**Comment by mr-brune** [comment]
I use https://github.com/ciromattia/kcc because the various kindle model
need the right image size. It only need a folder of images to convert the
folder to .mobi

Il gio 8 giu 2023, 11:00 Rahman Yusuf ***@***.***> ha scritto:

**Comment by mansuf** [comment]
Hello, this feature is added in commit https://github.com/mansuf/mangadex-downloader/commit/3f2de153bbe1b38899996c0d2af6137c635f5ca3 ([branch v3.0.0](https://github.com/mansuf/mangadex-downloader/tree/v3.0.0)).

You can start trying it now by installing development version (v3.0.0 branch) 

Installation with git + pip:

```
pip uninstall mangadex-downloader
pip install git+https://github.com/mansuf/mangadex-downloader.git@3f2de153bbe1b38899996c0d2af6137c635f5ca3
```

If you're installing mangadex-downloader from github releases, you can download the development version in here:

The download files are available in "artifacts" section

https://github.com/mansuf/mangadex-downloader/actions/runs/7285882431

----

You can now ignore missing chapters by adding `--ignore-missing-chapters` option

```sh
# Let's say you already downloaded the manga, and you moved the chapters somewhere else
# and you want to update it, but don't wanna download the moved (missing) chapters
mangadex-dl "insert URL here" --ignore-missing-chapters
```

**Please note that this option cannot be used with `--no-track` option**
