### ISSUE TITLE
Downloader seems to not recognize certain group

### ISSUE THREAD

**Issue by xADDBx** [mansuf/mangadex-downloader#71]
### What happened ?

When trying to download https://mangadex.org/title/35b9f818-926b-4f4a-aa2b-0ac068986a73/kabushiki-gaisha-magi-lumiere using the command ```mangadex-dl.exe --save-as cbz-volume https://mangadex.org/title/35b9f818-926b-4f4a-aa2b-0ac068986a73/kabushiki-gaisha-magi-lumiere``` it only downloads the first 3 chapters.
Since that seemed weird, I tried to specify the group for which all existing chapters (73) are uploaded with the command ```mangadex-dl.exe --group https://mangadex.org/group/4f1de6a2-f0c5-4ac5-bce5-02c7dbb67deb/mangaplus --save-as cbz-volume https://mangadex.org/title/35b9f818-926b-4f4a-aa2b-0ac068986a73/kabushiki-gaisha-magi-lumiere```.
The output:
![grafik](https://github.com/mansuf/mangadex-downloader/assets/62178123/f4d15a1d-b30d-409c-a3d2-e08c2367f153)
Meaning the downloader doesn't seem to recognize all 73 (+ side) chapters made by that group.

### What did you expect to happen ?

It should've automatically switched to the available scanlation group after chapter 3 and it should've downloaded all the groups Chapters after specifying them

### OS version

Windows 10 Pro 22H2
Build 19045.2965

### App version

mangadex-downloader: v2.9.1
Python: 3.10.11
arch: x64
bundled executable: yes

### Installation origin

Github releases

### Reproducible command

mangadex-dl.exe --save-as cbz-volume https://mangadex.org/title/35b9f818-926b-4f4a-aa2b-0ac068986a73/kabushiki-gaisha-magi-lumiere
mangadex-dl.exe --group https://mangadex.org/group/4f1de6a2-f0c5-4ac5-bce5-02c7dbb67deb/mangaplus --save-as cbz-volume https://mangadex.org/title/35b9f818-926b-4f4a-aa2b-0ac068986a73/kabushiki-gaisha-magi-lumiere

### Additional context

I successfully used the tool for quite a few different Manga. I can't exclude the possibility that I did something wrong though.

**Comment by mansuf** [comment]
The application is using filter to not show any chapters that doesn't contain images. 

Previously, the app will show message telling you that some chapters are not downloaded because there is no images in that chapter. This filter was done locally in the application itself. But now it was done in MangaDex API (Using parameter `includeEmptyPages` with value `0`)

**Comment by mansuf** [comment]
> At least it should be fixed

I mean the application did the right thing. If the chapters doesn't contain any images and it's just have redirect links, it will refuse to download that chapters.
