### ISSUE TITLE
Chapter sub-directory support

### ISSUE THREAD

**Issue by Mint-Tea-Jellyfish** [mansuf/mangadex-downloader#76]
### The idea

Create chapter sub directory in volume folders i.e Manganamefolder -> Volume.01 -> Chapter.03 -> img001.jpg

### Why this feature should be added to the app ?

Allows for proper folder structure before uploading to another site.

**Comment by mansuf** [comment]
I don't think that is possible. The purpose for volume formats is to wrap all chapters & images into 1 single folder or file, no sub directories needed.

Why don't use chapter formats instead ? (ex: `cbz`, `pdf`, `raw`)
