### ISSUE TITLE
Add placeholders support for `--path` option

### ISSUE THREAD

**Issue by kesinger** [mansuf/mangadex-downloader#85]
### The idea

It would be convenient if there were an option that I could set to change the "Vol " (and "No Volume") of filename construction here:

https://github.com/mansuf/mangadex-downloader/blob/28ba4b326df806f2baec9568595d89c018211258/mangadex_downloader/format/base.py#L252C13-L252C33

### Why this feature should be added to the app ?

I view dl'd manga on a tablet, and if I transfer two different manga on there I'll have two "Vol 1.epub", two "Vol 2.epub", and so on.  If I could specify the currently-fixed part of the file name I could have saved them as "Manga 1 Vol 1.epub", "Manga 2 Vol 1.epub", etc, and be able to tell which is which from the filename.

(I understand this is ultimately a problem with some other piece of software,  and it's easy enough for me to write a little script to rename things, but it never hurts to ask...)

**Comment by mansuf** [comment]
This feature currently planned in v3.0.0. You can check the progress in here #80

**Comment by mansuf** [comment]
Hello, sorry for taking so long, i got too busy in real life things.

Anyways, this feature has been added in [v3.0.0 branch](https://github.com/mansuf/mangadex-downloader/tree/v3.0.0) (commit https://github.com/mansuf/mangadex-downloader/commit/3e257fb5264c6e46ecb23ac1e45eb8f269d257f1)

You can start trying it now by installing development version (v3.0.0 branch) 

Installation with git + pip:

```
pip uninstall mangadex-downloader
pip install git+https://github.com/mansuf/mangadex-downloader.git@3e257fb5264c6e46ecb23ac1e45eb8f269d257f1
```

If you're installing mangadex-downloader from github releases, you can download the development version in here:

The download files are available in "artifacts" section

https://github.com/mansuf/mangadex-downloader/actions/runs/7248099641

-------

`--path` option are now absolute and you can use placeholders so you can customize as you like it.

Example usage:
```shell
# This will download to directory "/home/sussyuser/manga/Some manga title - some_random_id/English"
mangadex-dl "URL" --path "/home/sussyuser/manga/{manga.title} - {manga.id}/{language.full}" -lang English
```

For more information about path placeholders, you can read the documentation here -> https://mangadex-dl.mansuf.link/en/v3.0.0/cli_ref/path_placeholders.html

If you have a problem just let me know.
