### ISSUE TITLE
Generate ComicInfo.xml for volumes as well

### ISSUE THREAD

**Issue by AlexLJordan** [mansuf/mangadex-downloader#87]
### The idea

I noticed that the `ComicInfo.xml` is created for cbz format, but not for cbz-volume. 

Since volumes are more similar to the usual full books I put on my device, I'd love to use the cbz-volume option, also to reduce clutter.

But calibre (using the [EmbedComicMetadata](https://github.com/dickloraine/EmbedComicMetadata) plugin) relies on the `ComicInfo.xml` file to find out metadata like the name of author and series, which is currently not created for volumes.
 

### Why this feature should be added to the app ?

This would make it much nicer to read manga on e-readers in terms of whole volumes, instead of chapters, which can be only few pages at times.

**Comment by mansuf** [comment]
Hello, `ComicInfo.xml` file has been added into `cbz-volume` and `cbz-single` formats. You can try it now by installing development version.

Installation method with pip & git:

```
pip uninstall mangadex-downloader
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@0d0e724975f8ec963f46d9a9dea2e58d6f6adf19
```

Installation from Github Release:

You can download it from here (in "artifacts" section) -> https://github.com/mansuf/mangadex-downloader/actions/runs/8518332683
