### ISSUE TITLE
Add support for Kavita naming convention

### ISSUE THREAD

**Issue by Kisaragi-ng** [mansuf/mangadex-downloader#88]
### The idea

If possible, I'd like to request that the output name follows the Kavita naming convention, similar to how magadex's `--save-as "tachiyomi"` works.

In general, Kavita uses the following format:

```
Library Root
  ┖── Series Name
      ┖── Series Name.cbz
```

You can find more information in their documentation [here](https://wiki.kavitareader.com/en/guides/managing-your-files).

I've been using your work for a while to download mangadex to tachiyomi, but currently, I'm using Kavita on my desktop. It would be really helpful if this downloader also supported their naming conventions.

### Why this feature should be added to the app ?

Tachiyomi is widely used on mobile devices, but for desktop platforms, I believe Kavita is more user-friendly.

**Comment by mansuf** [comment]
> If possible, I'd like to request that the output name follows the Kavita naming convention, similar to how magadex's --save-as "tachiyomi" works.

Yes it's possible with `--filename` and `--path` options with placeholders support. But, this features are not ready yet, and i really don't have free time to working on it. See #80 for progress

Btw, do not use `--save-as tachiyomi` anymore, it's deprecated and you should use `--write-tachiyomi-info`

**Comment by mansuf** [comment]
Hello, sorry for taking so long, i got too busy in real life things.

Anyways, this feature has been added in [v3.0.0 branch](https://github.com/mansuf/mangadex-downloader/tree/v3.0.0) (commit https://github.com/mansuf/mangadex-downloader/commit/3698cf10aa22c14e1225000bffbff4f2a3b55c2e)

You can start trying it now by installing development version (v3.0.0 branch) 

Installation with git + pip:

```
pip uninstall mangadex-downloader
pip install git+https://github.com/mansuf/mangadex-downloader.git@3698cf10aa22c14e1225000bffbff4f2a3b55c2e
```

If you're installing mangadex-downloader from github releases, you can download the development version in here:

The download files are available in "artifacts" section

https://github.com/mansuf/mangadex-downloader/actions/runs/7249594589/

-------

You can now customize path to kavita naming convetion, like the example below:

Example usage:
```shell
# This will download to directory "/home/sussyuser/Library Root/Some manga title/"
# with filename "Some manga title Vol. 0 Ch. 12.cbz"
mangadex-dl "URL" --path "/home/sussyuser/manga/{manga.title}" -f cbz --filename-chapter "{chapter.manga_title} Vol.{chapter.volume} Ch.{chapter.chapter}{file_ext}"
```

For more information about path placeholders, you can read the documentation here -> https://mangadex-dl.mansuf.link/en/v3.0.0/cli_ref/path_placeholders.html

If you have a problem, issue or bug, you can re-open and comment in this issue tracker here.
