### ISSUE TITLE
[Feature Request] Ability to download different scanlation groups

### ISSUE THREAD

**Issue by nyaashaa** [mansuf/mangadex-downloader#9]
Some chapters have a different scanlation groups, is it possible to download all? Thanks!

**Comment by mansuf** [comment]
Yeah, but it's not implemented yet. I will try to add this feature, thanks for the suggestion !

**Comment by mansuf** [comment]
Feature added in https://github.com/mansuf/mangadex-downloader/commit/e116794fc4b220da85d2aafee1d439eb2ef7ab5b
