### ISSUE TITLE
Some manga doesn’t get downloaded fully

### ISSUE THREAD

**Issue by MatesSlaby** [mansuf/mangadex-downloader#90]
### What happened ?

I tried downloading the following url:
[https://mangadex.org/title/d8323b7b-9a7a-462b-90f0-2759fed52511/dosanko-gal-wa-namaramenkoi](url)
But it only downloads 50 of the 102 chapters.

### What did you expect to happen ?

I expected all the chapters to be downloaded.

### OS version

Windows 11 21H2

### App version

2.10.3

### Installation origin

Github releases

### Reproducible command

py -3 -m mangadex_downloader "https://mangadex.org/title/d8323b7b-9a7a-462b-90f0-2759fed52511/dosanko-gal-wa-namaramenkoi" --no-group-name --no-track --path D:\manga

### Additional context

After looking at MangaDex it seems that the downloader only downloads third party translations and not the official release, I couldn’t figure out how to force it to download official release.

**Comment by yyolk** [comment]
Those issues are to an external site so there's nothing for mangadex-dl to grab. This is detectable in the response from mangadex with the `externalUrl` property in the response for a `Chapter` or `MangaFeed`.

I'm not sure this would be considered a bug, necessarily. I believe the publisher works with mangadex in a way to give those issues away for free, so they're preferred over any scan groups.

Here's an annotated chapter response for one with `externalUrl`:
```json
{
  "result": "ok",
  "response": "entity",
  "data": {
    "id": "5c9f2600-d702-4bd1-b268-0e7be7ec2a7e",
    "type": "chapter",
    "attributes": {
      "volume": "1",
      "chapter": "3",
      "title": null,
      "translatedLanguage": "en",
      "externalUrl": "https://mangaplus.shueisha.co.jp/viewer/1007747",
      "publishAt": "2020-10-12T10:12:45+00:00",
      "readableAt": "2020-10-12T10:12:45+00:00",
      "createdAt": "2020-10-12T10:12:45+00:00",
      "updatedAt": "2022-12-08T23:03:40+00:00",
      "pages": 0,   // pages is 0
      "version": 2
    }
```

**Comment by MatesSlaby** [comment]
I know it’s not really a bug, but it was the most fitting github issue category.
I was wondering if it would be possible for mangadex downloader to grab the Manga plus versions of chapters, so that I wouldn’t need to use Manga plus specific downloaders like mloader.

**Comment by mansuf** [comment]
> I was wondering if it would be possible for mangadex downloader to grab the Manga plus versions of chapters, so that I wouldn’t need to use Manga plus specific downloaders like mloader.

Well, the name of the application says it all. It's downloader for MangaDex only. It cannot download from other sites. 

If i want to implement download from other sites, then i'm forced to change the name of application. But i don't have any interest doing that. Besides implementing all features from MangaDex is already painful for me.

**Comment by vonProteus** [comment]
@yyolk 
> This is detectable in the response from mangadex with the `externalUrl`

can we grab this url and pass it to another application/script from `mangadex-downloader`?
