### ISSUE TITLE
Skip already downloaded chapters (that were moved to other place)

### ISSUE THREAD

**Issue by brachna** [mansuf/mangadex-downloader#95]
Once downloaded I rename cbz archives with my script and put them into Kavita. So archives are not in the same place.
If I want to update chapters I get this:
```
[WARNING] '[Unknown] Ch. 167.5.cbz' is missing or unverified (hash is not matching)
[WARNING] Found 190 missing or unverified chapters, re-downloading 190 chapters...
```
There's download.db in series' folders, I would assume it can be used to avoid re-downloading everything.
Is there an option to skip this?

**Comment by mansuf** [comment]
Yeah, you can use `--no-track`. That option is to prevent create `download.db` file

**Comment by brachna** [comment]
I don't understand what this supposed to solve.
Yes, --no-track does not create download.db, but downloader still downloads missing chapters that were already downloaded.

**Comment by mansuf** [comment]
My apologies, i thought you want to disable download tracking feature (`download.db`). You just want to ignore missing chapters yes ?

If that's what you wanted, this feature has already been requested (#70) and it's in my to-do list #80 . Hopefully it will be done soon

**Comment by brachna** [comment]
Somehow missed that issue, closing as duplicate.

**Comment by mansuf** [comment]
Hello, this feature has been added in v3.0.0 branch.

You can install them now from development version. You can read #70 for more information about the installation.
