### ISSUE TITLE
Add command to download manga information only

### ISSUE THREAD

**Issue by Theo1996** [mansuf/mangadex-downloader#99]
### The idea

Add option to download a file with all the titles of the manga in the Library, even better if you can download small cover art ,author,artist,summary, multiple TLs of the title etc

### Why this feature should be added to the app ?

It is very important to have a backup of all the manga you are reading because like other website if it shuts down you are fucked.

**Comment by Theo1996** [comment]
What I meant is that if I select the "library" option it just prints 10 lines of manga titles and you need to type next for the next 10, I wan t to download just the titles/names of all my manga in my library to a text file or CSV.
If I use the cover command I need to do it for every manga title in my library manually.

**Comment by mansuf** [comment]
> What I meant is that if I select the "library" option it just prints 10 lines of manga titles and you need to type next for the next 10, I wan t to download just the titles/names of all my manga in my library to a text file or CSV.

No, it won't happen. But, you can do some hacking using internal API with python if you want to. 

**Just a reminder that the internal API can be changed at any time without notice.**

```python
from mangadex_downloader.network import Net
from mangadex_downloader.iterator import IteratorUserLibraryManga

# Login first
Net.mangadex.login(username="YOUR USERNAME", password="YOUR PASSWORD")

fp = open("manga titles.txt", "w+")
for manga in IteratorUserLibraryManga():
    fp.writelines(manga.title + "\n")
fp.close()
```

**Comment by Theo1996** [comment]
1.I dont really understand why it cant be done. The API limits to 100 manga names/IDs per request cant your script just continue sending new requests till the total number of IDs in the Library of a user is reached ? I have aprox 3500 manga, so it would send 35 requests and put all that in a text file or something.
2. I also saw a `limit ` variable in some part of your code which equals to "10", isnt that the 10 entries you get when requesting "library?"

**Comment by mansuf** [comment]
> I dont really understand why it cant be done. The API limits to 100 manga names/IDs per request cant your script just continue sending new requests till the total number of IDs in the Library of a user is reached ? I have aprox 3500 manga, so it would send 35 requests and put all that in a text file or something.

Command `library` are using `IteratorUserLibraryManga` class which i demonstrated how to get all manga from the user library with internal API. So from techincal perspective, the application is capable of retrieving all manga from the user library. And yes it respect API limits, so it would send multiple requests if the user have tons of manga in the library.

However, i don't understand when you say "just to download titles only", not to mention the other optional informations such as small cover art, author, artist, summary, multiple TLs of the title, etc. It's like download a manga in .cbz file and then remove chapters and images and you would left with `ComicInfo.xml` and the manga cover. And you also mention your purpose is to backup all manga from your library, which is doesn't make sense at all.

I'm not trying to be rude here, but can you explain more details why you want this feature ?

If you want to use this feature for analysis things (like this https://github.com/mansuf/mangadex-downloader/issues/60) because you say you wanna save manga titles to CSV file, i can create a separate command just for that.

> I also saw a limit  variable in some part of your code which equals to "10", isnt that the 10 entries you get when requesting "library" ? Cant that also be increased or set by the user(though that is not very important)?

The limit variable is for per page in `library` command, so when you using `library` command, you will be displayed first 10 manga that you have in the library, then if you want to see the next one, you could just type `next` and then it will display next 10 manga in the library.

**Comment by Theo1996** [comment]
What I suggested was to download JUST titles/name of the manga ,meaning only the text of the name that already appears in CMD, if you use the `library `command, in groups of 10. 
The optional information, which I dont really care for but is nice to have, are what you and I already mentioned, but together with the titles(name/text) of each manga would make a more rich(cover,tags) backup of my library index.
And by index I mean just a list of strings for every manga title/name.
**Basically the same thing that appears when I click on library in mangadex, but it has all 3500 titles instead of 100. Sorry for the misunderstanding.My original post wasnt clear enough.**
>If you want to use this feature for analysis things (like this https://github.com/mansuf/mangadex-downloader/issues/60) because you say you wanna save manga titles to CSV file, i can create a separate command just for that.


Yes, please.

> The limit variable is for per page in library command, so when you using library command, you will be displayed first 10 manga that you have in the library, then if you want to see the next one, you could just type next and then it will display next 10 manga in the library.

Yes ,I understood that.

**Comment by mansuf** [comment]
Alright, i will add this on my to-do list in [v3.0.0 PR ](https://github.com/mansuf/mangadex-downloader/pull/80). 

Keep in mind, i don't have ETA when this features is implemented, because i have to do other things (documentations, etc).

**Comment by Theo1996** [comment]
it works , but its only for individual manga urls. It was supposed to iterate over all the manga titles in library and save them all to a .csv.
`**Basically the same thing that appears when I click on library in mangadex, but it has all 3500 titles instead of 100. Sorry for the misunderstanding.My original post wasnt clear enough.**`

**Comment by mansuf** [comment]
You just have to modify `--manga-info-filepath` to somewhere else if you want it one place. By default it placed each manga folders

**Comment by Theo1996** [comment]
Modifying the filepath doesnt change the fact that it only works for for one manga URL that I provide, Didnt we agree it was supposed to download all the info of each title in library. I tried using the library command but it doesnt work with create-info. Like the quote I posted earlier.

**Comment by mansuf** [comment]
It works for `library` command and all other commands such as `list`, `followed-list`, `random`, etc

```
python -m mangadex_downloader "library" --login --login-username "REDACTED" --login-password "REDACTED" --create-manga-info --manga-info-filepath "./manga_info.{manga_info_format}" --input-pos "*" --path "G:\Test\Manga\DownloadTest"
```

Output:
[manga_info.csv](https://github.com/user-attachments/files/15594127/manga_info.csv)

**Comment by Theo1996** [comment]
I run your command and it start downloading the covers and creates a manga_info.csv but it fails on the second or third manga with the error :
`Traceback (most recent call last):
  File "E:\python\python310\lib\site-packages\mangadex_downloader\cli\__init__.py", line 87, in _main
    download(args)
  File "E:\python\python310\lib\site-packages\mangadex_downloader\cli\download.py", line 34, in download
    url(args, args.type)
  File "E:\python\python310\lib\site-packages\mangadex_downloader\cli\url.py", line 187, in __call__
    self.func(self.id, args)
  File "E:\python\python310\lib\site-packages\mangadex_downloader\cli\url.py", line 105, in download_manga
    dl_manga(*args)
  File "E:\python\python310\lib\site-packages\mangadex_downloader\main.py", line 200, in download
    download_manga(manga, formatted_path)
  File "E:\python\python310\lib\site-packages\mangadex_downloader\main.py", line 133, in download_manga
    create_manga_info(path, m, replace)
  File "E:\python\python310\lib\site-packages\mangadex_downloader\utils.py", line 363, in create_manga_info
    manga_info.write()
  File "E:\python\python310\lib\site-packages\mangadex_downloader\manga.py", line 320, in write
    self.write_to_csv()
  File "E:\python\python310\lib\site-packages\mangadex_downloader\manga.py", line 378, in write_to_csv
    writer.writerow(row)
  File "E:\python\python310\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'cp932' codec can't encode character '\u2014' in position 104: illegal multibyte sequence`

**Comment by mansuf** [comment]
Fixed in https://github.com/mansuf/mangadex-downloader/commit/a0fe2c5fb8b08153ff9f034b554dce85e5eb8897

Installtion with Git & pip

```sh
pip uninstall mangadex-downloader
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@a0fe2c5fb8b08153ff9f034b554dce85e5eb8897
```
